apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-world-service
spec:
  selector:
    app: hello-k8s-world
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
